/** Languages available via “Other languages” (not shown on the main grid). */
export const OTHER_LANGUAGES: readonly { value: string; label: string }[] = [
  { value: "arabic", label: "Arabic" },
  { value: "hindi", label: "Hindi" },
  { value: "dutch", label: "Dutch" },
  { value: "swedish", label: "Swedish" },
  { value: "polish", label: "Polish" },
  { value: "turkish", label: "Turkish" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "thai", label: "Thai" },
  { value: "greek", label: "Greek" },
  { value: "hebrew", label: "Hebrew" },
  { value: "czech", label: "Czech" },
  { value: "romanian", label: "Romanian" },
  { value: "hungarian", label: "Hungarian" },
  { value: "danish", label: "Danish" },
  { value: "norwegian", label: "Norwegian" },
  { value: "finnish", label: "Finnish" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "indonesian", label: "Indonesian" },
  { value: "malay", label: "Malay" },
  { value: "tagalog", label: "Tagalog" },
  { value: "bengali", label: "Bengali" },
  { value: "urdu", label: "Urdu" },
  { value: "persian", label: "Persian (Farsi)" },
  { value: "swahili", label: "Swahili" },
  { value: "catalan", label: "Catalan" },
  { value: "slovak", label: "Slovak" },
  { value: "croatian", label: "Croatian" },
  { value: "serbian", label: "Serbian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "latvian", label: "Latvian" },
  { value: "estonian", label: "Estonian" },
  { value: "icelandic", label: "Icelandic" },
  { value: "irish", label: "Irish" },
  { value: "welsh", label: "Welsh" },
  { value: "tamil", label: "Tamil" },
  { value: "telugu", label: "Telugu" },
  { value: "punjabi", label: "Punjabi" },
  { value: "marathi", label: "Marathi" },
  { value: "other", label: "Other / not listed" },
] as const;
